package fakedns.view;

import burp.BurpExtension;
import burp.api.montoya.MontoyaApi;
import extend.util.external.NetUtil;
import java.awt.Component;
import extension.burp.IBurpTab;
import extension.helpers.IpUtil;
import extension.helpers.StringUtil;
import extension.helpers.SwingUtil;
import extension.view.base.CustomTableModel;
import fakedns.model.HostNameItem;
import fakedns.model.FakeDnsProperty;
import fakedns.server.DnsHandler;
import fakedns.server.SimpleDnsServer;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.BindException;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isayan
 */
public class FakeDnsTab extends javax.swing.JPanel implements IBurpTab {

    private final static Logger logger = Logger.getLogger(FakeDnsTab.class.getName());

    private final static java.util.ResourceBundle RELEASE = java.util.ResourceBundle.getBundle("burp/resources/release");

    /**
     * Creates new form FakeDnsPanel
     */
    public FakeDnsTab() {
        initComponents();
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupInterface = new javax.swing.JPopupMenu();
        pnlHead = new javax.swing.JPanel();
        tglStartStopServer = new javax.swing.JToggleButton();
        lblExceptionMessage = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        lblBindIntarface = new javax.swing.JLabel();
        txtBindInterface = new javax.swing.JTextField();
        btnInterfaces = new javax.swing.JButton();
        lblFakeIP = new javax.swing.JLabel();
        txtFakeIPv4 = new javax.swing.JTextField();
        chkResolvSystemHost = new javax.swing.JCheckBox();
        chkResolvBurpHost = new javax.swing.JCheckBox();
        lblNameServers = new javax.swing.JLabel();
        txtNameServers = new javax.swing.JTextField();
        lblFakeDomain = new javax.swing.JLabel();
        scrollFakeDomains = new javax.swing.JScrollPane();
        tblFakeDomains = new javax.swing.JTable();
        btnPasteDomain = new javax.swing.JButton();
        btnAddAllDomain = new javax.swing.JButton();
        btnAddDomain = new javax.swing.JButton();
        btnEditDomain = new javax.swing.JButton();
        btnRemoveDomain = new javax.swing.JButton();
        btnRemoveAllDomain = new javax.swing.JButton();
        txtFakeIPv6 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        tglStartStopServer.setText("Start");
        tglStartStopServer.setMaximumSize(new java.awt.Dimension(150, 22));
        tglStartStopServer.setMinimumSize(new java.awt.Dimension(10, 22));
        tglStartStopServer.setPreferredSize(new java.awt.Dimension(100, 22));
        tglStartStopServer.addChangeListener(this::tglStartStopServerStateChanged);
        tglStartStopServer.addActionListener(this::tglStartStopServerActionPerformed);

        javax.swing.GroupLayout pnlHeadLayout = new javax.swing.GroupLayout(pnlHead);
        pnlHead.setLayout(pnlHeadLayout);
        pnlHeadLayout.setHorizontalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglStartStopServer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExceptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        pnlHeadLayout.setVerticalGroup(
            pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglStartStopServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExceptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglStartStopServer.getAccessibleContext().setAccessibleDescription("");

        add(pnlHead, java.awt.BorderLayout.NORTH);

        lblBindIntarface.setText("Bind Interface:");
        lblBindIntarface.setMaximumSize(new java.awt.Dimension(150, 16));
        lblBindIntarface.setMinimumSize(new java.awt.Dimension(10, 16));
        lblBindIntarface.setPreferredSize(new java.awt.Dimension(100, 16));

        txtBindInterface.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBindInterfaceFocusLost(evt);
            }
        });

        btnInterfaces.setText("▼");
        btnInterfaces.addActionListener(this::btnInterfacesActionPerformed);

        lblFakeIP.setText("Fake IP:");
        lblFakeIP.setMaximumSize(new java.awt.Dimension(150, 16));
        lblFakeIP.setMinimumSize(new java.awt.Dimension(10, 16));
        lblFakeIP.setPreferredSize(new java.awt.Dimension(100, 16));

        txtFakeIPv4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFakeIPv4FocusLost(evt);
            }
        });

        chkResolvSystemHost.setText("resolv system hosts");
        chkResolvSystemHost.addChangeListener(this::chkResolvSystemHostStateChanged);

        chkResolvBurpHost.setText("resolv burp hosts");
        chkResolvBurpHost.addChangeListener(this::chkResolvBurpHostStateChanged);

        lblNameServers.setText("Name Servers:");
        lblNameServers.setMaximumSize(new java.awt.Dimension(150, 16));
        lblNameServers.setMinimumSize(new java.awt.Dimension(10, 16));
        lblNameServers.setPreferredSize(new java.awt.Dimension(100, 16));

        txtNameServers.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameServersFocusLost(evt);
            }
        });

        lblFakeDomain.setText("Fake Domains:");
        lblFakeDomain.setMaximumSize(new java.awt.Dimension(150, 16));
        lblFakeDomain.setMinimumSize(new java.awt.Dimension(10, 16));
        lblFakeDomain.setPreferredSize(new java.awt.Dimension(100, 16));

        tblFakeDomains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enabled", "Domain", "IPaddress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFakeDomains.getTableHeader().setReorderingAllowed(false);
        scrollFakeDomains.setViewportView(tblFakeDomains);

        btnPasteDomain.setText("Paste domain");
        btnPasteDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnPasteDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnPasteDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnPasteDomain.addActionListener(this::btnPasteDomainActionPerformed);

        btnAddAllDomain.setText("Add All");
        btnAddAllDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnAddAllDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnAddAllDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnAddAllDomain.addActionListener(this::btnAddAllDomainActionPerformed);

        btnAddDomain.setText("Add");
        btnAddDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnAddDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnAddDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnAddDomain.addActionListener(this::btnAddDomainActionPerformed);

        btnEditDomain.setText("Edit");
        btnEditDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnEditDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnEditDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnEditDomain.addActionListener(this::btnEditDomainActionPerformed);

        btnRemoveDomain.setText("Remove");
        btnRemoveDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnRemoveDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnRemoveDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnRemoveDomain.addActionListener(this::btnRemoveDomainActionPerformed);

        btnRemoveAllDomain.setText("Remove All");
        btnRemoveAllDomain.setMaximumSize(new java.awt.Dimension(150, 22));
        btnRemoveAllDomain.setMinimumSize(new java.awt.Dimension(10, 22));
        btnRemoveAllDomain.setPreferredSize(new java.awt.Dimension(100, 22));
        btnRemoveAllDomain.addActionListener(this::btnRemoveAllDomainActionPerformed);

        txtFakeIPv6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFakeIPv6FocusLost(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblNameServers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFakeIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddAllDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveAllDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBindIntarface, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPasteDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFakeDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollFakeDomains)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(txtBindInterface, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnInterfaces))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(chkResolvBurpHost)
                                .addGap(18, 18, 18)
                                .addComponent(chkResolvSystemHost))
                            .addComponent(txtNameServers, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(txtFakeIPv4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFakeIPv6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 116, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindIntarface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBindInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInterfaces))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakeIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFakeIPv4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFakeIPv6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNameServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakeDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkResolvSystemHost)
                    .addComponent(chkResolvBurpHost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnPasteDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAllDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveAllDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollFakeDomains, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(pnlMain, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private CustomTableModel modelFakeDomains = null;

    @SuppressWarnings("unchecked")
    private void customizeComponents() {
        this.modelFakeDomains = new CustomTableModel(this.tblFakeDomains.getModel());
        this.tblFakeDomains.setModel(this.modelFakeDomains);
        this.tblFakeDomains.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        SwingUtil.addHintText(this.txtFakeIPv4, "127.0.0.1");
        SwingUtil.addHintText(this.txtFakeIPv6, "0:0:0:0:0:0:0:1");
        SwingUtil.addHintText(this.txtNameServers, "8.8.8.8,8.8.8.4");

        // selected
        this.tblFakeDomains.getColumnModel().getColumn(0).setMinWidth(30);
        this.tblFakeDomains.getColumnModel().getColumn(0).setPreferredWidth(50);
        this.tblFakeDomains.getColumnModel().getColumn(0).setMaxWidth(100);

        // Domain
        this.tblFakeDomains.getColumnModel().getColumn(1).setMinWidth(100);
        this.tblFakeDomains.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tblFakeDomains.getColumnModel().getColumn(1).setMaxWidth(300);

        // IP
        this.tblFakeDomains.getColumnModel().getColumn(2).setMinWidth(0);
        this.tblFakeDomains.getColumnModel().getColumn(2).setPreferredWidth(0);
        this.tblFakeDomains.getColumnModel().getColumn(2).setMaxWidth(0);

        int rowCount = this.tblFakeDomains.getSelectedRowCount();
        this.btnEditDomain.setEnabled((rowCount > 0));
        this.btnRemoveDomain.setEnabled((rowCount > 0));

        this.tblFakeDomains.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }
                int rowCount = tblFakeDomains.getSelectedRowCount();
                btnEditDomain.setEnabled((rowCount > 0));
                btnRemoveDomain.setEnabled((rowCount > 0));
            }
        });

    }

    public MontoyaApi api() {
        return BurpExtension.api();
    }

    private SimpleDnsServer server = null;

    public synchronized SimpleDnsServer getDnsServerInstance() {
        BurpExtension instance = BurpExtension.getInstance();
        if (instance != null) {
            return instance.getServer();
        } else {
            if (this.server == null) {
                this.server = new SimpleDnsServer(null);
            }
            this.server.setFakeDnsOption(this.getProperty());
            return this.server;
        }
    }

    private void btnAddAllDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllDomainActionPerformed
        this.showMultiLineDlg();
    }//GEN-LAST:event_btnAddAllDomainActionPerformed

    private void btnRemoveDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDomainActionPerformed
        this.removeDomainItem();
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnRemoveDomainActionPerformed

    private void tglStartStopServerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tglStartStopServerStateChanged
        if (evt.getSource() instanceof JToggleButton button) {
            button.setText(button.isSelected() ? "Stop" : "Start");
            setContainerEnable(!button.isSelected());
        }
    }//GEN-LAST:event_tglStartStopServerStateChanged

    private void tglStartStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglStartStopServerActionPerformed
        this.setErrorMessage("");
        final FakeDnsProperty option = this.getProperty();
        final SimpleDnsServer server = this.getDnsServerInstance();
        server.setEventHandler(new DnsHandler.MessageHandler() {

            @Override
            public void message(String message) {
                if (api() != null) {
                    api().logging().logToOutput(message);
                }
                else {
                    System.out.println(message);
                }
            }

            @Override
            public void catchException(Thread t, Throwable ex) {
                String message = "";
                if (ex instanceof BindException) {
                    message = "Bind Error: " + option.getBindInterface() + " - " + ex.getMessage();
                } else if (ex instanceof IOException) {
                    message = "Fatal Error: " + StringUtil.getStackTrace(ex.getMessage(), ex);
                }
                //tglStartServer.setSelected(false);
                setErrorMessage(message);
                if (api() != null) {
                    api().logging().logToError(ex.getMessage(), ex);
                }
                else {
                    System.err.println(message);
                }
                tglStartStopServer.setSelected(false);
            }

        });

        if (this.tglStartStopServer.isSelected()) {
            if (this.valid()) {
                server.setFakeDnsOption(this.getProperty());
                server.startServer();
            } else {
                this.tglStartStopServer.setSelected(false);
            }
        } else {
            server.stopServer();
        }
    }//GEN-LAST:event_tglStartStopServerActionPerformed

    private void btnPasteDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasteDomainActionPerformed
        String paste = SwingUtil.systemClipboardPaste();
        List<HostNameItem> fakeDomains = this.getFakeDomains();
        fakeDomains.addAll(HostNameItem.parseHostList(paste));
        this.setFakeDomains(fakeDomains);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnPasteDomainActionPerformed

    private void btnEditDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDomainActionPerformed
        this.showHostEntryDlg(true);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnEditDomainActionPerformed

    private void btnAddDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDomainActionPerformed
        this.showHostEntryDlg(false);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnAddDomainActionPerformed

    private void btnRemoveAllDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllDomainActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Delete all items?", null, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            if (tblFakeDomains.getModel() instanceof DefaultTableModel model) {
                this.removeAllDomainItem();
            }
        }
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnRemoveAllDomainActionPerformed

    private void chkResolvBurpHostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkResolvBurpHostStateChanged
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_chkResolvBurpHostStateChanged

    private void btnInterfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterfacesActionPerformed
        this.updatePopupMenuUI();
        Point pt = this.btnInterfaces.getLocation();
        this.popupInterface.show(this.pnlMain, pt.x, pt.y + this.btnInterfaces.getHeight());
    }//GEN-LAST:event_btnInterfacesActionPerformed

    private void chkResolvSystemHostStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkResolvSystemHostStateChanged
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_chkResolvSystemHostStateChanged

    private void txtBindInterfaceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBindInterfaceFocusLost
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_txtBindInterfaceFocusLost

    private void txtFakeIPv4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFakeIPv4FocusLost
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_txtFakeIPv4FocusLost

    private void txtFakeIPv6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFakeIPv6FocusLost
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_txtFakeIPv6FocusLost

    private void txtNameServersFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameServersFocusLost
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_txtNameServersFocusLost

    private void updatePopupMenuUI() {
        this.popupInterface.removeAll();
        List<InetAddress> inetList = NetUtil.getNetworkInterfaces();
        for (int i = 0; i < inetList.size(); i++) {
            JMenuItem item = new JMenuItem(inetList.get(i).getHostAddress());
            this.popupInterface.add(item);
            item.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    if (e.getSource() instanceof JMenuItem item) {
                        txtBindInterface.setText(item.getText());
                    }
                }
            });
        }
    }

    @Override
    public String getTabCaption() {
        return SimpleDnsServer.getTabCaption();
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAllDomain;
    private javax.swing.JButton btnAddDomain;
    private javax.swing.JButton btnEditDomain;
    private javax.swing.JButton btnInterfaces;
    private javax.swing.JButton btnPasteDomain;
    private javax.swing.JButton btnRemoveAllDomain;
    private javax.swing.JButton btnRemoveDomain;
    private javax.swing.JCheckBox chkResolvBurpHost;
    private javax.swing.JCheckBox chkResolvSystemHost;
    private javax.swing.JLabel lblBindIntarface;
    private javax.swing.JLabel lblExceptionMessage;
    private javax.swing.JLabel lblFakeDomain;
    private javax.swing.JLabel lblFakeIP;
    private javax.swing.JLabel lblNameServers;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPopupMenu popupInterface;
    private javax.swing.JScrollPane scrollFakeDomains;
    private javax.swing.JTable tblFakeDomains;
    private javax.swing.JToggleButton tglStartStopServer;
    private javax.swing.JTextField txtBindInterface;
    private javax.swing.JTextField txtFakeIPv4;
    private javax.swing.JTextField txtFakeIPv6;
    private javax.swing.JTextField txtNameServers;
    // End of variables declaration//GEN-END:variables

    public void setContainerEnable(boolean enable) {
        SwingUtil.setContainerEnable(this.pnlMain, enable);
        if (enable) {
            int rowCount = this.tblFakeDomains.getSelectedRowCount();
            this.btnEditDomain.setEnabled((rowCount > 0));
            this.btnRemoveDomain.setEnabled((rowCount > 0));
        }
    }

    public void setProperty(FakeDnsProperty property) {
        this.txtBindInterface.setText(property.getBindInterface());
        this.txtFakeIPv4.setText(property.getFakeIPv4());
        this.txtFakeIPv6.setText(property.getFakeIPv6());
        this.setFakeDomains(property.getFakeDomains());
        this.setNameServers(property.getNameServers());
        this.chkResolvBurpHost.setSelected(property.isResolvBurpHosts());
        this.chkResolvSystemHost.setSelected(property.isResolvSystemHosts());
    }

    public FakeDnsProperty getProperty() {
        FakeDnsProperty property = new FakeDnsProperty();
        property.setBindInterface(this.txtBindInterface.getText().trim());
        property.setFakeIPv4(this.txtFakeIPv4.getText().trim());
        property.setFakeIPv6(this.txtFakeIPv6.getText().trim());
        property.setFakeDomains(this.getFakeDomains());
        property.setNameServers(this.getNameServers());
        property.setResolvBurpHosts(this.chkResolvBurpHost.isSelected());
        property.setResolvSystemHosts(this.chkResolvSystemHost.isSelected());
        return property;
    }

    public void setStandalone(boolean value) {
        this.chkResolvBurpHost.setEnabled(!value);
    }

    private final HostEntryItemDlg hostEntryItemDlg = new HostEntryItemDlg(null, true);

    private void showHostEntryDlg(boolean editMode) {
        try {
            this.hostEntryItemDlg.setLocationRelativeTo(this);
            if (editMode) {
                this.hostEntryItemDlg.setPropery(this.getEditItem());
            } else {
                HostNameItem item = new HostNameItem(true, "");
                this.hostEntryItemDlg.setPropery(item);
            }

            this.hostEntryItemDlg.setVisible(true);
            if (this.hostEntryItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
                HostNameItem editItem = this.hostEntryItemDlg.getPropery();
                this.setEditItem(editItem, editMode);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    private final MultiItemDlg multiItemDlg = new MultiItemDlg(null, true);

    private void showMultiLineDlg() {
        try {
            this.multiItemDlg.setLocationRelativeTo(this);
            this.multiItemDlg.setMultiLine(new String[]{""});
            this.multiItemDlg.setVisible(true);
            if (this.multiItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
                String[] lines = this.multiItemDlg.getMultiLine();
                for (String line : lines) {
                    HostNameItem item = new HostNameItem();
                    item.setEnable(true);
                    item.setHostName(line);
                    this.setEditItem(item, false);
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    private void setEditItem(HostNameItem item, boolean update) {
        Object[] rows = HostNameItem.toObjects(item);
        SwingUtil.addOrUpdateItem(this.tblFakeDomains, rows, update);
    }

    private void removeDomainItem() {
        SwingUtil.removeItem(this.tblFakeDomains);
    }

    private void removeAllDomainItem() {
        SwingUtil.removeAllItem(this.tblFakeDomains);
    }

    private HostNameItem getEditItem() {
        HostNameItem item = new HostNameItem();
        Object editCols[] = SwingUtil.editItem(this.tblFakeDomains);
        if (editCols != null) {
            item = HostNameItem.fromObjects(editCols);
        }
        return item;
    }

    public List<HostNameItem> getFakeDomains() {
        javax.swing.JTable srcTable = this.tblFakeDomains;
        List<HostNameItem> list = new ArrayList<>();
        for (int i = 0; i < srcTable.getRowCount(); i++) {
            Object editRows[] = this.modelFakeDomains.getRows(i);
            list.add(HostNameItem.fromObjects(editRows));
        }
        return list;
    }

    public void setFakeDomains(List<HostNameItem> list) {
        this.modelFakeDomains.removeAll();
        for (int i = 0; i < list.size(); i++) {
            HostNameItem bean = list.get(i);
            Object editRows[] = HostNameItem.toObjects(bean);
            this.modelFakeDomains.addRow(editRows);
        }
    }

    private void setNameServers(List<HostNameItem> nameServers) {
        this.txtNameServers.setText(HostNameItem.joinHostList(",", nameServers));
    }

    private List<HostNameItem> getNameServers() {
        final List<HostNameItem> list = HostNameItem.parseHostList(this.txtNameServers.getText());
        return list;
    }

    public boolean valid() {
        FakeDnsProperty fakeDnsOption = this.getProperty();
        if (!(IpUtil.isIPv4Address(fakeDnsOption.getBindInterface()) || IpUtil.isIPv6Address(fakeDnsOption.getBindInterface()))) {
            this.setErrorMessage("interface IPv4 or IPv6 format error:" + fakeDnsOption.getBindInterface());
            return false;
        }
        if (!fakeDnsOption.isEmptyFakeIPv4() && !IpUtil.isIPv4Address(fakeDnsOption.getFakeIPv4())) {
            this.setErrorMessage("fakeip IPv4 format error:" + fakeDnsOption.getFakeIPv4());
            return false;
        }
        if (!fakeDnsOption.isEmptyFakeIPv6() && !IpUtil.isIPv6Address(fakeDnsOption.getFakeIPv6())) {
            this.setErrorMessage("fakeip IPv6 format error:" + fakeDnsOption.getFakeIPv6());
            return false;
        }
        if (fakeDnsOption.isEmptyFakeIPv4() && fakeDnsOption.isEmptyFakeIPv6()) {
            this.setErrorMessage("fakeip has not been specified");
            return false;
        }

        List<HostNameItem> nameserverList = fakeDnsOption.getNameServers();
        for (HostNameItem item : nameserverList) {
            if (!(IpUtil.isIPv4Address(item.getHostName()) || IpUtil.isIPv6Address(item.getHostName()))) {
                this.setErrorMessage("nameserver format error: " + item.getHostName());
                return false;
            }
        }
        return true;
    }

    public void setErrorMessage(String message) {
        this.lblExceptionMessage.setText(message);
    }

}
