package fakedns.view;

import burp.BurpExtension;
import burp.api.montoya.MontoyaApi;
import java.awt.Component;
import extension.burp.IBurpTab;
import extension.helpers.IpUtil;
import extension.helpers.StringUtil;
import extension.helpers.SwingUtil;
import extension.view.base.CustomTableModel;
import fakedns.model.HostNameItem;
import fakedns.model.FakeDnsProperty;
import fakedns.server.DnsHandler;
import fakedns.server.SimpleDnsServer;
import java.io.IOException;
import java.net.BindException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isayan
 */
public class FakeDnsTab extends javax.swing.JPanel implements IBurpTab {

    private final static Logger logger = Logger.getLogger(FakeDnsTab.class.getName());

    /**
     * Creates new form FakeDnsPanel
     */
    public FakeDnsTab() {
        initComponents();
        customizeComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglStartServer = new javax.swing.JToggleButton();
        lblFakeIP = new javax.swing.JLabel();
        txtBindInterface = new javax.swing.JTextField();
        lblFakeDomain = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFakeDomains = new javax.swing.JTable();
        btnPasteDomain = new javax.swing.JButton();
        btnAddAllDomain = new javax.swing.JButton();
        btnEditDomain = new javax.swing.JButton();
        btnRemoveDomain = new javax.swing.JButton();
        lblBindIntarface = new javax.swing.JLabel();
        txtFakeIP = new javax.swing.JTextField();
        lblExceptionMessage = new javax.swing.JLabel();
        btnAddDomain = new javax.swing.JButton();
        btnRemoveAllDomain = new javax.swing.JButton();
        lblFakeServers = new javax.swing.JLabel();
        txtFakeServers = new javax.swing.JTextField();

        tglStartServer.setText("Start");
        tglStartServer.addChangeListener(this::tglStartServerStateChanged);
        tglStartServer.addActionListener(this::tglStartServerActionPerformed);

        lblFakeIP.setText("Fake IP:");

        lblFakeDomain.setText("Fake Domains:");

        tblFakeDomains.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "chk", "Domain", "IPaddress"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFakeDomains.setColumnSelectionAllowed(true);
        tblFakeDomains.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblFakeDomains);
        tblFakeDomains.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        btnPasteDomain.setText("Paste domain");
        btnPasteDomain.addActionListener(this::btnPasteDomainActionPerformed);

        btnAddAllDomain.setText("Add All");
        btnAddAllDomain.addActionListener(this::btnAddAllDomainActionPerformed);

        btnEditDomain.setText("Edit");
        btnEditDomain.addActionListener(this::btnEditDomainActionPerformed);

        btnRemoveDomain.setText("Remove");
        btnRemoveDomain.addActionListener(this::btnRemoveDomainActionPerformed);

        lblBindIntarface.setText("Bind Interface:");

        btnAddDomain.setText("Add");
        btnAddDomain.addActionListener(this::btnAddDomainActionPerformed);

        btnRemoveAllDomain.setText("Remove All");
        btnRemoveAllDomain.addActionListener(this::btnRemoveAllDomainActionPerformed);

        lblFakeServers.setText("Name Servers:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblFakeIP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFakeServers, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tglStartServer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFakeDomain, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveDomain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveAllDomain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEditDomain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddDomain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddAllDomain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPasteDomain, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(lblBindIntarface, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1142, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFakeServers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                                .addComponent(txtFakeIP, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBindInterface, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(lblExceptionMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglStartServer)
                    .addComponent(lblExceptionMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindIntarface)
                    .addComponent(txtBindInterface, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFakeIP)
                    .addComponent(txtFakeIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFakeServers)
                    .addComponent(txtFakeServers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFakeDomain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPasteDomain)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddAllDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveDomain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveAllDomain, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglStartServer.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAllDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllDomainActionPerformed
        this.showMultiLineDlg();
    }//GEN-LAST:event_btnAddAllDomainActionPerformed

    private void btnRemoveDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDomainActionPerformed
        this.removeDomainItem();
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnRemoveDomainActionPerformed

    private void tglStartServerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tglStartServerStateChanged
        if (evt.getSource() instanceof JToggleButton button) {
            button.setText(button.isSelected() ? "Stop" : "Start");
        }
    }//GEN-LAST:event_tglStartServerStateChanged

    public MontoyaApi api() {
        return BurpExtension.api();
    }

    public SimpleDnsServer getDnsServer() {
        BurpExtension instance = BurpExtension.getInstance();
        if (instance != null) {
            return instance.getServer();
        } else {
            SimpleDnsServer server = new SimpleDnsServer(null);
            server.setFakeDnsOption(this.getProperty());
            return server;
        }
    }

    private void tglStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglStartServerActionPerformed
        this.setErrorMessage("");
        final FakeDnsProperty option = this.getProperty();
        final SimpleDnsServer server = this.getDnsServer();
        server.setEventHandler(new DnsHandler.MessageHandler() {

            @Override
            public void message(String message) {
                if (api() != null) {
                    api().logging().logToOutput(message);
                }
            }

            @Override
            public void catchException(Thread t, Throwable ex) {
                String message = "";
                if (ex instanceof BindException) {
                    message = "Bind Error: " + option.getBindInterface() + " - " + ex.getMessage();
                } else if (ex instanceof IOException) {
                    message = "Fatal Error: " + StringUtil.getStackTrace(ex.getMessage(), ex);
                }
                //tglStartServer.setSelected(false);
                setErrorMessage(message);
                if (api() != null) {
                    api().logging().logToError(ex.getMessage(), ex);
                }
                tglStartServer.setSelected(false);
            }

        });

        if (this.tglStartServer.isSelected()) {
            if (valid()) {
                server.setFakeDnsOption(this.getProperty());
                server.startServer();
            } else {
                this.tglStartServer.setSelected(false);
            }
        } else {
            server.stopServer();
        }
    }//GEN-LAST:event_tglStartServerActionPerformed

    private void btnPasteDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasteDomainActionPerformed
        String paste = SwingUtil.systemClipboardPaste();
        List<HostNameItem> fakeDomains = this.getFakeDomains();
        fakeDomains.addAll(HostNameItem.parseHostList(paste));
        this.setFakeDomains(fakeDomains);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnPasteDomainActionPerformed

    private void btnEditDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditDomainActionPerformed
        this.showHostEntryDlg(true);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnEditDomainActionPerformed

    private void btnAddDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDomainActionPerformed
        this.showHostEntryDlg(false);
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnAddDomainActionPerformed

    private void btnRemoveAllDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveAllDomainActionPerformed
       int result = JOptionPane.showConfirmDialog(this,"Delete all items?", null, JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            if (tblFakeDomains.getModel() instanceof DefaultTableModel model) {
                this.removeAllDomainItem();
            }
        }
        this.firePropertyChange(FakeDnsProperty.FAKEDNS_PROPERTY, null, this.getProperty());
    }//GEN-LAST:event_btnRemoveAllDomainActionPerformed

    private CustomTableModel modelFakeDomains = null;

    @SuppressWarnings("unchecked")
    private void customizeComponents() {
        this.modelFakeDomains = new CustomTableModel(this.tblFakeDomains.getModel());
        this.tblFakeDomains.setModel(this.modelFakeDomains);
        this.tblFakeDomains.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        // selected
        this.tblFakeDomains.getColumnModel().getColumn(0).setMinWidth(20);
        this.tblFakeDomains.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.tblFakeDomains.getColumnModel().getColumn(0).setMaxWidth(30);

        // Domain
        this.tblFakeDomains.getColumnModel().getColumn(1).setMinWidth(100);
        this.tblFakeDomains.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tblFakeDomains.getColumnModel().getColumn(1).setMaxWidth(300);

        // IP
        this.tblFakeDomains.getColumnModel().getColumn(2).setMinWidth(0);
        this.tblFakeDomains.getColumnModel().getColumn(2).setPreferredWidth(0);
        this.tblFakeDomains.getColumnModel().getColumn(2).setMaxWidth(0);

        int rowCount = this.tblFakeDomains.getSelectedRowCount();
        this.btnEditDomain.setEnabled((rowCount > 0));
        this.btnRemoveDomain.setEnabled((rowCount > 0));

        this.tblFakeDomains.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    return;
                }
                int rowCount = tblFakeDomains.getSelectedRowCount();
                btnEditDomain.setEnabled((rowCount > 0));
                btnRemoveDomain.setEnabled((rowCount > 0));
            }
        });

    }

    @Override
    public String getTabCaption() {
        return "Fake DNS";
    }

    @Override
    public Component getUiComponent() {
        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAllDomain;
    private javax.swing.JButton btnAddDomain;
    private javax.swing.JButton btnEditDomain;
    private javax.swing.JButton btnPasteDomain;
    private javax.swing.JButton btnRemoveAllDomain;
    private javax.swing.JButton btnRemoveDomain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBindIntarface;
    private javax.swing.JLabel lblExceptionMessage;
    private javax.swing.JLabel lblFakeDomain;
    private javax.swing.JLabel lblFakeIP;
    private javax.swing.JLabel lblFakeServers;
    private javax.swing.JTable tblFakeDomains;
    private javax.swing.JToggleButton tglStartServer;
    private javax.swing.JTextField txtBindInterface;
    private javax.swing.JTextField txtFakeIP;
    private javax.swing.JTextField txtFakeServers;
    // End of variables declaration//GEN-END:variables

    public void setProperty(FakeDnsProperty property) {
        this.txtBindInterface.setText(property.getBindInterface());
        this.txtFakeIP.setText(property.getFakeIP());
        setFakeDomains(property.getFakeDomains());
    }

    public FakeDnsProperty getProperty() {
        FakeDnsProperty property = new FakeDnsProperty();
        property.setBindInterface(this.txtBindInterface.getText());
        property.setFakeIP(this.txtFakeIP.getText());
        property.setFakeDomains(this.getFakeDomains());
        property.setNameServers(this.getNameServers());
        return property;
    }

    private final HostEntryItemDlg hostEntryItemDlg = new HostEntryItemDlg(null, true);

    private void showHostEntryDlg(boolean editMode) {
        try {
            this.hostEntryItemDlg.setLocationRelativeTo(this);
            if (editMode) {
                this.hostEntryItemDlg.setPropery(this.getEditItem());
            } else {
                HostNameItem item = new HostNameItem(true,"");
                this.hostEntryItemDlg.setPropery(item);
            }

            this.hostEntryItemDlg.setVisible(true);
            if (this.hostEntryItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
                HostNameItem editItem = this.hostEntryItemDlg.getPropery();
                this.setEditItem(editItem, editMode);
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    private final MultiItemDlg multiItemDlg = new MultiItemDlg(null, true);

    private void showMultiLineDlg() {
        try {
            this.multiItemDlg.setLocationRelativeTo(this);
            this.multiItemDlg.setMultiLine(new String[]{""});
            this.multiItemDlg.setVisible(true);
            if (this.multiItemDlg.getModalResult() == JOptionPane.OK_OPTION) {
                String[] lines = this.multiItemDlg.getMultiLine();
                for (String line : lines) {
                    HostNameItem item = new HostNameItem();
                    item.setEnable(true);
                    item.setHostName(line);
                    this.setEditItem(item, false);
                }
            }
        } catch (Exception ex) {
            logger.log(Level.SEVERE, ex.getMessage(), ex);
        }
    }

    private void setEditItem(HostNameItem item, boolean update) {
        Object[] rows = HostNameItem.toObjects(item);
        SwingUtil.addOrUpdateItem(this.tblFakeDomains, rows, update);
    }

    private void removeDomainItem() {
        SwingUtil.removeItem(this.tblFakeDomains);
    }

    private void removeAllDomainItem() {
        SwingUtil.removeAllItem(this.tblFakeDomains);
    }

    private HostNameItem getEditItem() {
        HostNameItem item = new HostNameItem();
        Object editCols[] = SwingUtil.editItem(this.tblFakeDomains);
        if (editCols != null) {
            item = HostNameItem.fromObjects(editCols);
        }
        return item;
    }

    public List<HostNameItem> getFakeDomains() {
        javax.swing.JTable srcTable = this.tblFakeDomains;
        List<HostNameItem> list = new ArrayList<>();
        for (int i = 0; i < srcTable.getRowCount(); i++) {
            Object editRows[] = this.modelFakeDomains.getRows(i);
            list.add(HostNameItem.fromObjects(editRows));
        }
        return list;
    }

    public void setFakeDomains(List<HostNameItem> list) {
        this.modelFakeDomains.removeAll();
        for (int i = 0; i < list.size(); i++) {
            HostNameItem bean = list.get(i);
            Object editRows[] = HostNameItem.toObjects(bean);
            this.modelFakeDomains.addRow(editRows);
        }
    }

    private List<HostNameItem> getNameServers() {
        final List<HostNameItem> list = HostNameItem.parseHostList(this.txtFakeServers.getText());
        return list;
    }

    public boolean valid() {
        FakeDnsProperty fakeDnsOption = this.getProperty();
        if (!IpUtil.isIPv4Address(fakeDnsOption.getBindInterface())) {
            this.setErrorMessage("interface ipv4 format error:" + fakeDnsOption.getBindInterface());
            return false;
        }
        if (!IpUtil.isIPv4Address(fakeDnsOption.getFakeIP())) {
            this.setErrorMessage("fakeip ipv4 format error:" + fakeDnsOption.getFakeIP());
            return false;
        }
        return true;
    }

    public void setErrorMessage(String message) {
        this.lblExceptionMessage.setText(message);
    }


}
